import "@ctrl-chat/ui/globals.css";
import { cn } from "@ctrl-chat/ui/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark no-scrollbars")}>
        {children}
      </body>
    </html>
  );
}
